<!DOCTYPE HTML>
<html>
<head>
    <title>Asif Abdullah Zamee - CV</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
    <link rel="stylesheet" href="assets/css/main.css" />
    <noscript><link rel="stylesheet" href="assets/css/noscript.css" /></noscript>
</head>
<body class="is-preload">

    <!-- Wrapper -->
    <div id="wrapper">

        <!-- Header -->
        <header id="header">
            <div class="logo">
                <span class="icon fa-user"></span>
            </div>
            <div class="content">
                <div class="inner">
                    <h1>ASIF ABDULLAH ZAMEE</h1>
                    <p>Aspiring Electrical Engineer | Machine Learning Enthusiast</p>
                </div>
            </div>
            <nav>
                <ul>
                    <li><a href="#intro">Introduction</a></li>
                    <li><a href="#work">Work</a></li>
                    <li><a href="#education">Education</a></li>
                    <li><a href="#contact">Contact</a></li>
                </ul>
            </nav>
        </header>

        <!-- Main -->
        <div id="main">

            <!-- Intro -->
            <article id="intro">
                <h2 class="major">Introduction</h2>
                <span class="image main"><img src="images/pp.jpeg" alt="Profile Picture" /></span>
                <p>I am a passionate Electrical and Electronics Engineering graduate with extensive experience in developing innovative solutions like fire mitigation systems. My expertise spans machine learning, image processing, and embedded systems.</p>
            </article>

            <!-- Work -->
            <article id="work">
                <h2 class="major">Work</h2>
                <span class="image main"><img src="images/work.jpg" alt="Work Showcase" /></span>
                <ul>
                    <li><b>Fire Mitigation System:</b> Integrated YOLOv8 for fire detection, later optimized with NCNN for Raspberry Pi performance.</li>
                    <li><b>Face Tracking:</b> Developed a servo-controlled face-tracking system using Raspberry Pi and image processing techniques.</li>
                    <li><b>Image Processing Projects:</b> Implemented advanced techniques like contrast stretching, noise reduction, and unsharp masking.</li>
                </ul>
            </article>

            <!-- Education -->
            <article id="education">
                <h2 class="major">Education</h2>
                <ul>
                    <li><b>BSc in Electrical and Electronics Engineering</b>, BRAC University (2020–2025), Dhaka, Major in Robotics, Machine Learning, and AI (Final Semester).</li>
                    <li><b>Higher Secondary Certificate</b>, Bangladesh Navy School and College (2016–2018), Chattogram, GPA: 4.25/5.00.</li>
                    <li><b>Secondary School Certificate</b>, Bangladesh Navy School and College (2014–2016), Chattogram, GPA: 5.00/5.00.</li>
                </ul>
            </article>

            <!-- Contact -->
            <article id="contact">
                <h2 class="major">Contact</h2>
                <form method="post" action="#">
                    <div class="fields">
                        <div class="field half">
                            <label for="name">Name</label>
                            <input type="text" name="name" id="name" />
                        </div>
                        <div class="field half">
                            <label for="email">Email</label>
                            <input type="text" name="email" id="email" />
                        </div>
                        <div class="field">
                            <label for="message">Message</label>
                            <textarea name="message" id="message" rows="4"></textarea>
                        </div>
                    </div>
                    <ul class="actions">
                        <li><input type="submit" value="Send Message" class="primary" /></li>
                        <li><input type="reset" value="Reset" /></li>
                    </ul>
                </form>
                <ul class="icons">
                    <li><a href="https://github.com/yourgithub" class="icon brands fa-github"><span class="label">GitHub</span></a></li>
                    <li><a href="https://linkedin.com/in/asif-abdullah-zamee-66408774" class="icon brands fa-linkedin"><span class="label">LinkedIn</span></a></li>
                </ul>
            </article>

        </div>

        <!-- Footer -->
        <footer id="footer">
            <p class="copyright">&copy; Asif Abdullah Zamee. Design: <a href="https://html5up.net">HTML5 UP</a>.</p>
        </footer>

    </div>

    <!-- BG -->
    <div id="bg"></div>

    <!-- Scripts -->
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/js/browser.min.js"></script>
    <script src="assets/js/breakpoints.min.js"></script>
    <script src="assets/js/util.js"></script>
    <script src="assets/js/main.js"></script>

</body>
</html>
